/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hib.hibernate.swing.designing;

/**
 *
 * @author tanis
 */
public class faqWindow extends javax.swing.JFrame {

    /**
     * Creates new form faqWindow
     */
    public faqWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setBackground(new java.awt.Color(153, 153, 153));
        jLabel39.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("When do I have to pay the rental fees?");
        jLabel39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 430, 30));

        jLabel43.setBackground(new java.awt.Color(153, 153, 153));
        jLabel43.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Can I pick up or return the car outside of opening hours");
        jLabel43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 430, 30));

        jLabel45.setBackground(new java.awt.Color(153, 153, 153));
        jLabel45.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Do the fees vary by region and season?");
        jLabel45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 430, 30));

        jLabel46.setBackground(new java.awt.Color(0, 0, 0));
        jLabel46.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 204, 255));
        jLabel46.setText("Please pay the fees when picking up the vehicle at the rental station.");
        jLabel46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 860, 30));

        jLabel42.setBackground(new java.awt.Color(0, 0, 0));
        jLabel42.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 204, 255));
        jLabel42.setText("Yes. Rental fees vary in accordance with both the region and the season.");
        jLabel42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 860, 30));

        jLabel44.setBackground(new java.awt.Color(0, 0, 0));
        jLabel44.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 204, 255));
        jLabel44.setText("No. Please pick up and return the vehicle within the opening hours of the concerned station.");
        jLabel44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 860, 30));

        jLabel41.setBackground(new java.awt.Color(153, 153, 153));
        jLabel41.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("What do I need to keep in mind when returning the car? ");
        jLabel41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 430, 30));

        jLabel40.setBackground(new java.awt.Color(0, 0, 0));
        jLabel40.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 204, 255));
        jLabel40.setText("Please make sure that you have not left anything inside the vehicle. We cannot be held responsible for any forgotten items.");
        jLabel40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 860, 30));

        jLabel38.setBackground(new java.awt.Color(153, 153, 153));
        jLabel38.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("              FAQs");
        jLabel38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 430, 40));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hib/hibernate/swing/designing/MAINLOGO.jpg"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hib/hibernate/swing/designing/HOME.jpg"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 77, -1));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hib/hibernate/swing/designing/wp4966861.jpg"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new flash().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(faqWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(faqWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(faqWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(faqWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new faqWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    // End of variables declaration//GEN-END:variables
}
